spring:
    config:
        import:
            - classpath:/dev/properties/application-dev.yml
#        activate:
#            on-profile: dev
#    profiles:
#        active:dev
    datasource:
        url: jdbc:mariadb://localhost:3306/weather
        username: root
        password: Rlarkems10#
        driver-class-name: org.mariadb.jdbc.Driver

server:
    port:8080